using System;
using UnityEngine;

namespace LightSide
{
    /// <summary>
    /// Scripts for which OpenGlyph supports dictionary-based word segmentation
    /// (Unicode line-break class SA — written without inter-word spaces).
    /// </summary>
    public enum SegmentationScript
    {
        /// <summary>Thai (U+0E00–U+0E7F).</summary>
        Thai = 0,
        /// <summary>Lao (U+0E80–U+0EFF).</summary>
        Lao = 1,
        /// <summary>Khmer (U+1780–U+17FF).</summary>
        Khmer = 2,
        /// <summary>Myanmar / Burmese (U+1000–U+109F).</summary>
        Myanmar = 3,
    }

    /// <summary>
    /// One opt-in segmentation dictionary assignment: which script a dictionary asset
    /// enables. Referenced from <see cref="UniTextSettings"/>. The dictionary asset is a
    /// compact OGSD trie binary generated offline (see <c>Tools~/DictGen</c>); it lives
    /// in a regular project folder (e.g. <c>Dictionaries/</c>), NOT under Resources, so
    /// only scripts you actually assign are pulled into a player build.
    /// </summary>
    [Serializable]
    public sealed class SegmentationDictionaryEntry
    {
        [Tooltip("The script this dictionary provides word boundaries for.")]
        public SegmentationScript script;

        [Tooltip("The OGSD dictionary .bytes asset (a TextAsset). Generated by Tools~/DictGen from " +
                 "the pinned ICU dictionaries. Leave empty to disable segmentation for this script.")]
        public TextAsset dictionary;
    }
}
